base.url=https://wo5cdjz6re.execute-api.us-east-1.amazonaws.com
auth.token=your_token_here
login.endpoint=/stage/api/graphql/user
dms.url=https://dms-backend-stage.simpleenergy.in
payment.url=https://payments-stage.simpleenergy.in